{{- if .Values.experimental.kubernetesGateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: traefik-gateway
  namespace: {{ default (include "traefik.namespace" .) .Values.experimental.kubernetesGateway.namespace }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
  {{- with .Values.experimental.kubernetesGateway.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.experimental.kubernetesGateway.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      port: {{ .Values.ports.web.port }}
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: websecure-st0rmingbr4in
      port: 443
      protocol: HTTPS
      hostname: "*.st0rmingbr4in.com"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - name: st0rmingbr4in.com-cert
            group: core
            kind: Secret
    - name: websecure-aphorya
      port: 443
      protocol: HTTPS
      hostname: "*.aphorya.fr"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - name: aphorya.fr-cert
            group: core
            kind: Secret
{{- end }}
